window.APP_DATA = {
  dataRevision: "2026-07-14-user-plans-1",
  bankCash: 245500,
  accounts: [
    {
      id: "self",
      label: "",
      name: "梦想号",
      availableCash: 152549.76
    },
    {
      id: "family",
      label: "",
      name: "私募号",
      availableCash: 440384.19
    }
  ],
  holdings: [
    {
      id: "self-002242",
      accountId: "self",
      name: "九阳股份",
      code: "002242",
      shares: 20000,
      cost: 11.174,
      currentPrice: 8.07,
      marketValueOverride: 161400,
      floatingPnlOverride: -62183.33,
      floatingPnlAdjustment: -103.33,
      strategyType: "遗留修复型",
      status: "7.5短打观察",
      risk: "只做7.5附近短线反弹仓，不变成长线加仓；跌破7.30不继续补；跌破7.00重新看主营和财报。",
      extraNote: "九阳7.5短打规则更新版：只做短线反弹仓；触发价7.50附近；首笔上限3000股、总量最多5000股；第一目标8.00；第二目标8.30-8.50；买入后60天没回到8.00则暂停，后续若财报确认主营利润修复，再重新评估是否提高策略等级。"
    },
    {
      id: "self-002594",
      accountId: "self",
      name: "比亚迪",
      code: "002594",
      shares: 600,
      availableShares: 600,
      cost: 90,
      currentPrice: 89.35,
      marketValueOverride: 53610,
      floatingPnlOverride: -390,
      floatingPnlAdjustment: 0,
      strategyType: "波段做T型",
      status: "做T观察仓",
      risk: "区分95-105的大波段与80-95的小波段，结合趋势、频率和胜率执行。",
      extraNote: "目前持有600股，计划每档做T 200股。"
    },
    {
      id: "family-002594",
      accountId: "family",
      name: "比亚迪",
      code: "002594",
      shares: 1400,
      cost: 83.95,
      currentPrice: 89.29,
      marketValueOverride: 125006,
      floatingPnlOverride: 7476,
      floatingPnlAdjustment: 0,
      strategyType: "长期持有型",
      status: "波段持仓",
      risk: "家庭私募仓位以节奏控制为主，不追高加仓",
      extraNote: "兴业证券家庭私募账户当前持有 1400 股。"
    },
    {
      id: "family-600900",
      accountId: "family",
      name: "长江电力",
      code: "600900",
      shares: 600,
      cost: 26.74,
      currentPrice: 28.5,
      marketValueOverride: 17100,
      floatingPnlOverride: 1056,
      floatingPnlAdjustment: 0,
      strategyType: "防守股息型",
      status: "防守底仓",
      risk: "长江不是高频T标的，不做密集网格",
      extraNote: ""
    },
    {
      id: "family-600036",
      accountId: "self",
      name: "招商银行",
      code: "600036",
      shares: 200,
      cost: 37.02,
      currentPrice: 37.08,
      marketValueOverride: 7416,
      floatingPnlOverride: 12,
      floatingPnlAdjustment: 0,
      strategyType: "长期持有型",
      status: "核心池观察",
      risk: "银行估值便宜不等于没有风险",
      extraNote: ""
    },
    {
      id: "family-600895",
      accountId: "self",
      name: "张江高科",
      code: "600895",
      shares: 1200,
      cost: 36.63,
      currentPrice: 35.27,
      marketValueOverride: 42324,
      floatingPnlOverride: -1632,
      floatingPnlAdjustment: 0,
      strategyType: "遗留退出型",
      status: "遗留修复与退出",
      risk: "以三年窗口、年复利8%为目标；最终卖出计划与做T计划分开管理。",
      extraNote: "三年期内合计盈利3次即可达到计划盈利收益。"
    }
  ],
  positionLots: [
    { id: "self-002242-initial", holdingId: "self-002242", side: "buy", label: "目前持仓", price: 11.174, shares: 20000, source: "initial" },
    { id: "self-002594-initial", holdingId: "self-002594", side: "buy", label: "目前持仓", price: 90, shares: 600, source: "initial" },
    { id: "family-002594-initial", holdingId: "family-002594", side: "buy", label: "目前持仓", price: 83.95, shares: 1400, source: "initial" },
    { id: "family-600900-initial", holdingId: "family-600900", side: "buy", label: "目前持仓", price: 26.74, shares: 600, source: "initial" },
    { id: "family-600036-initial", holdingId: "family-600036", side: "buy", label: "目前持仓", price: 37.02, shares: 200, source: "initial" },
    { id: "family-600895-initial", holdingId: "family-600895", side: "buy", label: "原持仓", price: 36.63, shares: 1200, source: "initial" },
    { id: "zjg-t-3-cycle-2-sell", holdingId: "family-600895", side: "sell", label: "T卖出第2次", price: 36.8, shares: 300, source: "trade" },
    { id: "zjg-t-4-cycle-1-sell", holdingId: "family-600895", side: "sell", label: "T卖出第1次", price: 34.62, shares: 300, source: "trade" },
    { id: "byd-self-t-3-cycle-1-sell", holdingId: "self-002594", side: "sell", label: "T卖出第1次", price: 90.09, shares: 200, source: "trade" }
  ],
  legacyPlans: [
    {
      id: "jy-plan-1",
      label: "计划1",
      holdingId: "self-002242",
      type: "买入",
      triggerPrice: 7.5,
      shares: 3000,
      status: "未触发",
      note: "7.50附近只做短线反弹仓，首笔上限3000股",
      applied: false
    },
    {
      id: "jy-plan-2",
      label: "计划2",
      holdingId: "self-002242",
      type: "卖出",
      triggerPrice: 8,
      shares: 3000,
      status: "未触发",
      note: "第一目标位，先看能否回到8.00",
      applied: false
    },
    {
      id: "jy-plan-3",
      label: "计划3",
      holdingId: "self-002242",
      type: "卖出",
      triggerPrice: 8.3,
      shares: 2000,
      status: "未触发",
      note: "第二目标下沿，开始兑现短打仓",
      applied: false
    },
    {
      id: "jy-plan-4",
      label: "计划4",
      holdingId: "self-002242",
      type: "卖出",
      triggerPrice: 8.5,
      shares: 2000,
      status: "未触发",
      note: "第二目标上沿，完成这一轮短打处理",
      applied: false
    },
    {
      id: "jy-plan-5",
      label: "计划5",
      holdingId: "self-002242",
      type: "观察",
      triggerPrice: 7.3,
      shares: null,
      status: "未触发",
      note: "跌破7.30不继续补仓",
      applied: false
    },
    {
      id: "jy-plan-6",
      label: "计划6",
      holdingId: "self-002242",
      type: "观察",
      triggerPrice: 7,
      shares: null,
      status: "未触发",
      note: "跌破7.00必须重新看主营和财报",
      applied: false
    },
    {
      id: "jy-plan-7",
      label: "计划7",
      holdingId: "self-002242",
      type: "观察",
      triggerPrice: null,
      shares: null,
      status: "未触发",
      note: "买入后60天没回8.00则暂停；财报确认主营利润修复后再评估提升策略等级",
      applied: false
    },
    {
      id: "byd-plan-1",
      label: "计划1",
      holdingId: "self-002594",
      type: "观察",
      triggerPrice: null,
      shares: null,
      status: "未触发",
      note: "本人账户暂不新增，等待复核",
      applied: false
    },
    {
      id: "family-byd-plan-1",
      label: "计划1",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 81,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-2",
      label: "计划2",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 79.785,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-3",
      label: "计划3",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 78.59,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-4",
      label: "计划4",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 77.41,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-5",
      label: "计划5",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 76.25,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-6",
      label: "计划6",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 75.105,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-7",
      label: "计划7",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 73.98,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-8",
      label: "计划8",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 72.87,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-9",
      label: "计划9",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 71.775,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-10",
      label: "计划10",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 70.7,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-11",
      label: "计划11",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 69.64,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-12",
      label: "计划12",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 68.595,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-13",
      label: "计划13",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 67.565,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-14",
      label: "计划14",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 66.55,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "cjdl-plan-1",
      label: "计划1",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 26,
      shares: null,
      status: "未触发",
      note: "26-28 小额打底",
      applied: false
    },
    {
      id: "cjdl-plan-2",
      label: "计划2",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 25,
      shares: null,
      status: "未触发",
      note: "25-26 正常补仓",
      applied: false
    },
    {
      id: "cjdl-plan-3",
      label: "计划3",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 23,
      shares: null,
      status: "未触发",
      note: "23-25 加速补仓",
      applied: false
    },
    {
      id: "cjdl-plan-4",
      label: "计划4",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 22,
      shares: null,
      status: "未触发",
      note: "22 以下重点补仓",
      applied: false
    },
    {
      id: "cjdl-plan-5",
      label: "计划5",
      holdingId: "family-600900",
      type: "卖出",
      triggerPrice: 31,
      shares: null,
      status: "未触发",
      note: "31 以上评估减仓",
      applied: false
    },
    {
      id: "cjdl-plan-6",
      label: "计划6",
      holdingId: "family-600900",
      type: "卖出",
      triggerPrice: 33,
      shares: null,
      status: "未触发",
      note: "33 以上明显偏贵，可减一部分",
      applied: false
    },
    {
      id: "cjdl-plan-7",
      label: "计划7",
      holdingId: "family-600900",
      type: "卖出",
      triggerPrice: 37,
      shares: null,
      status: "未触发",
      note: "梦想价位，可大幅减仓",
      applied: false
    },
    {
      id: "cmb-plan-1",
      label: "计划1",
      holdingId: "family-600036",
      type: "观察",
      triggerPrice: null,
      shares: null,
      status: "未触发",
      note: "等待风控通过后再分批增持",
      applied: false
    },
    {
      id: "zjgk-plan-1",
      label: "计划1",
      holdingId: "family-600895",
      type: "观察",
      triggerPrice: 37.64,
      shares: 600,
      status: "未触发",
      note: "等待确认卖出计划",
      applied: false
    }
  ],
  plans: [
    { id: "zjg-buy-1", holdingId: "family-600895", kind: "buy", sequence: 1, operation: "/", buyPrice: 33.066, buyShares: 300, status: "未触发", note: "补入后加入计划卖出的仓位，具体分配待定" },
    { id: "zjg-buy-2", holdingId: "family-600895", kind: "buy", sequence: 2, operation: "/", buyPrice: 31.158, buyShares: 300, status: "未触发", note: "补入后加入计划卖出的仓位，具体分配待定" },
    { id: "zjg-sell-1", holdingId: "family-600895", kind: "buy", sequence: 3, operation: "/", buyPrice: 36.63, buyShares: 1200, dreamPrice: 46.63, selldpShares: 1200, holdingBased: true, status: "未触发", note: "3年窗口，年复利8%；DP最终退出，不计划买回" },
    { id: "zjg-t-1", holdingId: "family-600895", kind: "trade", sequence: 1, operation: "/", sellPrice: 40.72, sellShares: 300, buyPrice: 36.648, status: "未触发", cycleNo: 1 },
    { id: "zjg-t-2", holdingId: "family-600895", kind: "trade", sequence: 2, operation: "/", sellPrice: 38.63, sellShares: 300, buyPrice: 34.767, status: "未触发", cycleNo: 1 },
    { id: "zjg-t-3", holdingId: "family-600895", kind: "trade", sequence: 3, operation: "已卖出", sellPrice: 36.74, sellShares: 300, buyPrice: 33.066, actualSellPrice: 36.8, actualTradeShares: 300, status: "已卖出", cycleNo: 2 },
    { id: "zjg-t-4", holdingId: "family-600895", kind: "trade", sequence: 4, operation: "已卖出", sellPrice: 34.62, sellShares: 300, buyPrice: 31.158, actualSellPrice: 34.62, actualTradeShares: 300, status: "已卖出", cycleNo: 1 },

    { id: "cmb-sell-1", holdingId: "family-600036", kind: "buy", sequence: 1, operation: "/", buyPrice: 37.02, buyShares: 200, dreamPrice: 40.7242, selldpShares: 200, holdingBased: true, status: "未触发", note: "DP计划全部卖出" },

    { id: "jy-t-1", holdingId: "self-002242", kind: "trade", sequence: 1, operation: "/", sellPrice: 9.8, sellShares: 1000, buyPrice: 8.9, status: "未触发", cycleNo: 1 },
    { id: "jy-t-2", holdingId: "self-002242", kind: "trade", sequence: 2, operation: "/", sellPrice: 10.09, sellShares: 1100, buyPrice: 8.75, status: "未触发", cycleNo: 1 },
    { id: "jy-t-3", holdingId: "self-002242", kind: "trade", sequence: 3, operation: "/", sellPrice: 10.4, sellShares: 1100, buyPrice: 8.69, status: "未触发", cycleNo: 1 },
    { id: "jy-t-4", holdingId: "self-002242", kind: "trade", sequence: 4, operation: "/", sellPrice: 10.71, sellShares: 1100, buyPrice: 8.63, status: "未触发", cycleNo: 1 },
    { id: "jy-t-5", holdingId: "self-002242", kind: "trade", sequence: 5, operation: "/", sellPrice: 11.03, sellShares: 1100, buyPrice: 8.57, status: "未触发", cycleNo: 1 },
    { id: "jy-t-6", holdingId: "self-002242", kind: "trade", sequence: 6, operation: "/", sellPrice: 11.36, sellShares: 1100, buyPrice: 8.51, status: "未触发", cycleNo: 1 },
    { id: "jy-t-7", holdingId: "self-002242", kind: "trade", sequence: 7, operation: "/", sellPrice: 11.7, sellShares: 1100, buyPrice: 8.45, status: "未触发", cycleNo: 1 },
    { id: "jy-t-8", holdingId: "self-002242", kind: "trade", sequence: 8, operation: "/", sellPrice: 12.05, sellShares: 1200, buyPrice: 8.39, status: "未触发", cycleNo: 1 },
    { id: "jy-t-9", holdingId: "self-002242", kind: "trade", sequence: 9, operation: "/", sellPrice: 12.41, sellShares: 1200, buyPrice: 8.33, status: "未触发", cycleNo: 1 },
    { id: "jy-sell-1", holdingId: "self-002242", kind: "buy", sequence: 1, operation: "/", buyPrice: 11.174, buyShares: 20000, dreamPrice: 16, selldpShares: 10000, holdingBased: true, status: "未触发", note: "DP梦想价最终退出/大幅减仓，不计划买回" },

    { id: "byd-self-t-1", holdingId: "self-002594", kind: "trade", sequence: 1, operation: "/", sellPrice: 94, sellShares: 200, buyPrice: 83, status: "未触发", cycleNo: 1 },
    { id: "byd-self-t-2", holdingId: "self-002594", kind: "trade", sequence: 2, operation: "/", sellPrice: 92, sellShares: 200, buyPrice: 81, status: "未触发", cycleNo: 1 },
    { id: "byd-self-t-3", holdingId: "self-002594", kind: "trade", sequence: 3, operation: "已卖出", sellPrice: 90, sellShares: 200, buyPrice: 79, actualSellPrice: 90.09, actualTradeShares: 200, status: "已卖出", cycleNo: 1 },

    { id: "byd-family-buy-1", holdingId: "family-002594", kind: "buy", sequence: 1, operation: "/", buyPrice: 78, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-2", holdingId: "family-002594", kind: "buy", sequence: 2, operation: "/", buyPrice: 77.22, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-3", holdingId: "family-002594", kind: "buy", sequence: 3, operation: "/", buyPrice: 76.45, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-4", holdingId: "family-002594", kind: "buy", sequence: 4, operation: "/", buyPrice: 75.68, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-5", holdingId: "family-002594", kind: "buy", sequence: 5, operation: "/", buyPrice: 74.93, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-6", holdingId: "family-002594", kind: "buy", sequence: 6, operation: "/", buyPrice: 74.18, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-7", holdingId: "family-002594", kind: "buy", sequence: 7, operation: "/", buyPrice: 73.44, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-8", holdingId: "family-002594", kind: "buy", sequence: 8, operation: "/", buyPrice: 72.7, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-9", holdingId: "family-002594", kind: "buy", sequence: 9, operation: "/", buyPrice: 71.97, buyShares: 100, status: "未触发" },
    { id: "byd-family-buy-10", holdingId: "family-002594", kind: "buy", sequence: 10, operation: "/", buyPrice: 71.25, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-11", holdingId: "family-002594", kind: "buy", sequence: 11, operation: "/", buyPrice: 70.54, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-12", holdingId: "family-002594", kind: "buy", sequence: 12, operation: "/", buyPrice: 69.84, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-13", holdingId: "family-002594", kind: "buy", sequence: 13, operation: "/", buyPrice: 69.14, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-14", holdingId: "family-002594", kind: "buy", sequence: 14, operation: "/", buyPrice: 68.45, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-15", holdingId: "family-002594", kind: "buy", sequence: 15, operation: "/", buyPrice: 67.76, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-16", holdingId: "family-002594", kind: "buy", sequence: 16, operation: "/", buyPrice: 67.08, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-17", holdingId: "family-002594", kind: "buy", sequence: 17, operation: "/", buyPrice: 66.41, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-18", holdingId: "family-002594", kind: "buy", sequence: 18, operation: "/", buyPrice: 65.75, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-19", holdingId: "family-002594", kind: "buy", sequence: 19, operation: "/", buyPrice: 65.09, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-20", holdingId: "family-002594", kind: "buy", sequence: 20, operation: "/", buyPrice: 64.44, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-21", holdingId: "family-002594", kind: "buy", sequence: 21, operation: "/", buyPrice: 63.8, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-22", holdingId: "family-002594", kind: "buy", sequence: 22, operation: "/", buyPrice: 63.16, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-23", holdingId: "family-002594", kind: "buy", sequence: 23, operation: "/", buyPrice: 62.53, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-24", holdingId: "family-002594", kind: "buy", sequence: 24, operation: "/", buyPrice: 61.9, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-25", holdingId: "family-002594", kind: "buy", sequence: 25, operation: "/", buyPrice: 61.28, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-26", holdingId: "family-002594", kind: "buy", sequence: 26, operation: "/", buyPrice: 60.67, buyShares: 200, status: "未触发" },
    { id: "byd-family-buy-27", holdingId: "family-002594", kind: "buy", sequence: 27, operation: "/", buyPrice: 60.06, buyShares: 300, status: "未触发" },
    { id: "byd-family-buy-28", holdingId: "family-002594", kind: "buy", sequence: 28, operation: "/", buyPrice: 59.46, buyShares: 300, status: "未触发" },
    { id: "byd-family-buy-29", holdingId: "family-002594", kind: "buy", sequence: 29, operation: "/", buyPrice: 58.87, buyShares: 300, status: "未触发" },
    { id: "byd-family-buy-30", holdingId: "family-002594", kind: "buy", sequence: 30, operation: "/", buyPrice: 58.28, buyShares: 300, status: "未触发" },
    { id: "byd-family-buy-31", holdingId: "family-002594", kind: "buy", sequence: 31, operation: "/", buyPrice: 57.7, buyShares: 300, status: "未触发" },
    { id: "byd-family-buy-32", holdingId: "family-002594", kind: "buy", sequence: 32, operation: "/", buyPrice: 57.12, buyShares: 300, status: "未触发" },
    { id: "byd-family-buy-33", holdingId: "family-002594", kind: "buy", sequence: 33, operation: "/", buyPrice: 56.55, buyShares: 300, status: "未触发" },
    { id: "byd-family-buy-34", holdingId: "family-002594", kind: "buy", sequence: 34, operation: "/", buyPrice: 55.98, buyShares: 300, status: "未触发" },

    { id: "cjdl-buy-1", holdingId: "family-600900", kind: "buy", sequence: 1, operation: "/", buyPrice: 26.21, buyShares: 600, status: "未触发" },
    { id: "cjdl-buy-2", holdingId: "family-600900", kind: "buy", sequence: 2, operation: "/", buyPrice: 25.68, buyShares: 600, status: "未触发" },
    { id: "cjdl-buy-3", holdingId: "family-600900", kind: "buy", sequence: 3, operation: "/", buyPrice: 25.17, buyShares: 700, status: "未触发" },
    { id: "cjdl-buy-4", holdingId: "family-600900", kind: "buy", sequence: 4, operation: "/", buyPrice: 24.66, buyShares: 700, status: "未触发" },
    { id: "cjdl-buy-5", holdingId: "family-600900", kind: "buy", sequence: 5, operation: "/", buyPrice: 24.17, buyShares: 700, status: "未触发" },
    { id: "cjdl-buy-6", holdingId: "family-600900", kind: "buy", sequence: 6, operation: "/", buyPrice: 23.69, buyShares: 700, status: "未触发" },
    { id: "cjdl-buy-7", holdingId: "family-600900", kind: "buy", sequence: 7, operation: "/", buyPrice: 23.21, buyShares: 800, status: "未触发" },
    { id: "cjdl-buy-8", holdingId: "family-600900", kind: "buy", sequence: 8, operation: "/", buyPrice: 22.75, buyShares: 800, status: "未触发" },
    { id: "cjdl-buy-9", holdingId: "family-600900", kind: "buy", sequence: 9, operation: "/", buyPrice: 22.29, buyShares: 800, status: "未触发" },
    { id: "cjdl-buy-10", holdingId: "family-600900", kind: "buy", sequence: 10, operation: "/", buyPrice: 21.85, buyShares: 800, status: "未触发" },
    { id: "cjdl-buy-11", holdingId: "family-600900", kind: "buy", sequence: 11, operation: "/", buyPrice: 21.41, buyShares: 900, status: "未触发" },
    { id: "cjdl-buy-12", holdingId: "family-600900", kind: "buy", sequence: 12, operation: "/", buyPrice: 20.98, buyShares: 900, status: "未触发" },
    { id: "cjdl-buy-13", holdingId: "family-600900", kind: "buy", sequence: 13, operation: "/", buyPrice: 20.56, buyShares: 900, status: "未触发" },
    { id: "cjdl-buy-14", holdingId: "family-600900", kind: "buy", sequence: 14, operation: "/", buyPrice: 20.15, buyShares: 900, status: "未触发" },
    { id: "cjdl-buy-15", holdingId: "family-600900", kind: "buy", sequence: 15, operation: "/", buyPrice: 19.75, buyShares: 1000, status: "未触发" },
    { id: "cjdl-buy-16", holdingId: "family-600900", kind: "buy", sequence: 16, operation: "/", buyPrice: 19.35, buyShares: 1000, status: "未触发" },
    { id: "cjdl-buy-17", holdingId: "family-600900", kind: "buy", sequence: 17, operation: "/", buyPrice: 18.97, buyShares: 1000, status: "未触发" },
    { id: "cjdl-buy-18", holdingId: "family-600900", kind: "buy", sequence: 18, operation: "/", buyPrice: 18.59, buyShares: 1000, status: "未触发" },
    { id: "cjdl-buy-19", holdingId: "family-600900", kind: "buy", sequence: 19, operation: "/", buyPrice: 18.22, buyShares: 1200, status: "未触发" },
    { id: "cjdl-buy-20", holdingId: "family-600900", kind: "buy", sequence: 20, operation: "/", buyPrice: 17.85, buyShares: 1200, status: "未触发" },
    { id: "cjdl-buy-21", holdingId: "family-600900", kind: "buy", sequence: 21, operation: "/", buyPrice: 17.49, buyShares: 1200, status: "未触发" }
  ],
  tradeHistory: [
    { id: "zjg-history-1", holdingId: "family-600895", planId: "zjg-t-3", cycleNo: 1, sellPrice: 36.74, shares: 300, buyPrice: 33.5, profit: 972, completedAt: "" }
  ]
};

// 2026-07-22 22:52 券商持仓截图快照。保留原有计划与历史，只校准当前账户和持仓。
(function applyBrokerSnapshot() {
  const snapshotAccounts = {
    self: { name: "华福证券（**1348）", availableCash: 844.63, repoBalance: 209000, repoShares: 2090, repoPrice: 100 },
    family: { name: "兴业证券（**7977）", availableCash: 100743.14, repoBalance: 300000, repoShares: 0, repoPrice: 100 }
  };
  const snapshotHoldings = [
    { id: "self-002242", accountId: "self", name: "九阳股份", code: "002242", shares: 20000, availableShares: 20000, cost: 11.174, currentPrice: 8.190, marketValueOverride: 163800, floatingPnlOverride: -59784.86, floatingPnlAdjustment: -104.86 },
    { id: "family-002594", accountId: "family", name: "比亚迪", code: "002594", shares: 1400, availableShares: 1400, cost: 83.951, currentPrice: 91.570, marketValueOverride: 128198, floatingPnlOverride: 10584.14, floatingPnlAdjustment: -82.46 },
    { id: "family-600036", accountId: "family", name: "招商银行", code: "600036", shares: 200, availableShares: 200, cost: 37.022, currentPrice: 38.710, marketValueOverride: 7742, floatingPnlOverride: 327.57, floatingPnlAdjustment: -10.03 },
    { id: "family-600895", accountId: "family", name: "张江高科", code: "600895", shares: 2100, availableShares: 2100, cost: 32.049, currentPrice: 27.730, marketValueOverride: 58233, floatingPnlOverride: -9108.30, floatingPnlAdjustment: -38.40 },
    { id: "family-600900", accountId: "family", name: "长江电力", code: "600900", shares: 600, availableShares: 600, cost: 25.950, currentPrice: 29.090, marketValueOverride: 17454, floatingPnlOverride: 1868.94, floatingPnlAdjustment: -15.06 }
  ];
  window.APP_DATA.accounts = window.APP_DATA.accounts.map((account) => ({ ...account, ...(snapshotAccounts[account.id] || {}) }));
  const snapshotIds = new Set(snapshotHoldings.map((holding) => holding.id));
  window.APP_DATA.holdings = window.APP_DATA.holdings.filter((holding) => holding.id !== "self-002594" && !snapshotIds.has(holding.id)).concat(snapshotHoldings);
  window.APP_DATA.positionLots = window.APP_DATA.positionLots.filter((lot) => lot.holdingId !== "self-002594" && !snapshotIds.has(lot.holdingId)).concat(snapshotHoldings.map((holding) => ({ id: `${holding.id}-snapshot-20260722`, holdingId: holding.id, side: "buy", label: "2026-07-22券商持仓快照", price: holding.cost, shares: holding.shares, source: "snapshot" })));
})();
