window.APP_DATA = {
  dataRevision: "2026-07-14-actual-3",
  bankCash: 245500,
  accounts: [
    {
      id: "self",
      label: "华福证券 **1348",
      name: "本人账户",
      availableCash: 152549.76
    },
    {
      id: "family",
      label: "兴业证券 **7977",
      name: "家庭私募账号",
      availableCash: 440384.19
    }
  ],
  holdings: [
    {
      id: "self-002242",
      accountId: "self",
      name: "九阳股份",
      code: "002242",
      shares: 20000,
      cost: 11.174,
      currentPrice: 8.07,
      marketValueOverride: 161400,
      floatingPnlOverride: -62183.33,
      floatingPnlAdjustment: -103.33,
      status: "7.5短打观察",
      risk: "只做7.5附近短线反弹仓，不变成长线加仓；跌破7.30不继续补；跌破7.00重新看主营和财报。",
      extraNote: "九阳7.5短打规则更新版：只做短线反弹仓；触发价7.50附近；首笔上限3000股、总量最多5000股；第一目标8.00；第二目标8.30-8.50；买入后60天没回到8.00则暂停，后续若财报确认主营利润修复，再重新评估是否提高策略等级。"
    },
    {
      id: "self-002594",
      accountId: "self",
      name: "比亚迪",
      code: "002594",
      shares: 600,
      cost: 90.413,
      currentPrice: 89.35,
      marketValueOverride: 53610,
      floatingPnlOverride: -672.62,
      floatingPnlAdjustment: -34.82,
      status: "观察仓",
      risk: "等待利润质量和 ROIC 拐点，不机械补仓",
      extraNote: "华福证券本人账户当前持有 600 股。"
    },
    {
      id: "family-002594",
      accountId: "family",
      name: "比亚迪",
      code: "002594",
      shares: 1400,
      cost: 83.951,
      currentPrice: 89.29,
      marketValueOverride: 125006,
      floatingPnlOverride: 7394.23,
      floatingPnlAdjustment: -80.37,
      status: "波段持仓",
      risk: "家庭私募仓位以节奏控制为主，不追高加仓",
      extraNote: "兴业证券家庭私募账户当前持有 1400 股。"
    },
    {
      id: "family-600900",
      accountId: "family",
      name: "长江电力",
      code: "600900",
      shares: 600,
      cost: 26.74,
      currentPrice: 28.5,
      marketValueOverride: 17100,
      floatingPnlOverride: 1041.12,
      floatingPnlAdjustment: -14.88,
      status: "防守底仓",
      risk: "长江不是高频T标的，不做密集网格",
      extraNote: ""
    },
    {
      id: "family-600036",
      accountId: "family",
      name: "招商银行",
      code: "600036",
      shares: 200,
      cost: 37.022,
      currentPrice: 37.08,
      marketValueOverride: 7416,
      floatingPnlOverride: 1.74,
      floatingPnlAdjustment: -9.86,
      status: "核心池观察",
      risk: "银行估值便宜不等于没有风险",
      extraNote: ""
    },
    {
      id: "family-600895",
      accountId: "family",
      name: "张江高科",
      code: "600895",
      shares: 600,
      cost: 36.017,
      currentPrice: 35.27,
      marketValueOverride: 21162,
      floatingPnlOverride: -464.86,
      floatingPnlAdjustment: -16.66,
      status: "遗留退出仓",
      risk: "不新增、不补仓、不做T；反弹分批卖出",
      extraNote: ""
    }
  ],
  plans: [
    {
      id: "jy-plan-1",
      label: "计划1",
      holdingId: "self-002242",
      type: "买入",
      triggerPrice: 7.5,
      shares: 3000,
      status: "未触发",
      note: "7.50附近只做短线反弹仓，首笔上限3000股",
      applied: false
    },
    {
      id: "jy-plan-2",
      label: "计划2",
      holdingId: "self-002242",
      type: "卖出",
      triggerPrice: 8,
      shares: 3000,
      status: "未触发",
      note: "第一目标位，先看能否回到8.00",
      applied: false
    },
    {
      id: "jy-plan-3",
      label: "计划3",
      holdingId: "self-002242",
      type: "卖出",
      triggerPrice: 8.3,
      shares: 2000,
      status: "未触发",
      note: "第二目标下沿，开始兑现短打仓",
      applied: false
    },
    {
      id: "jy-plan-4",
      label: "计划4",
      holdingId: "self-002242",
      type: "卖出",
      triggerPrice: 8.5,
      shares: 2000,
      status: "未触发",
      note: "第二目标上沿，完成这一轮短打处理",
      applied: false
    },
    {
      id: "jy-plan-5",
      label: "计划5",
      holdingId: "self-002242",
      type: "观察",
      triggerPrice: 7.3,
      shares: null,
      status: "未触发",
      note: "跌破7.30不继续补仓",
      applied: false
    },
    {
      id: "jy-plan-6",
      label: "计划6",
      holdingId: "self-002242",
      type: "观察",
      triggerPrice: 7,
      shares: null,
      status: "未触发",
      note: "跌破7.00必须重新看主营和财报",
      applied: false
    },
    {
      id: "jy-plan-7",
      label: "计划7",
      holdingId: "self-002242",
      type: "观察",
      triggerPrice: null,
      shares: null,
      status: "未触发",
      note: "买入后60天没回8.00则暂停；财报确认主营利润修复后再评估提升策略等级",
      applied: false
    },
    {
      id: "byd-plan-1",
      label: "计划1",
      holdingId: "self-002594",
      type: "观察",
      triggerPrice: null,
      shares: null,
      status: "未触发",
      note: "本人账户暂不新增，等待复核",
      applied: false
    },
    {
      id: "family-byd-plan-1",
      label: "计划1",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 81,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-2",
      label: "计划2",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 79.785,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-3",
      label: "计划3",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 78.59,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-4",
      label: "计划4",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 77.41,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-5",
      label: "计划5",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 76.25,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-6",
      label: "计划6",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 75.105,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-7",
      label: "计划7",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 73.98,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-8",
      label: "计划8",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 72.87,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-9",
      label: "计划9",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 71.775,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-10",
      label: "计划10",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 70.7,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-11",
      label: "计划11",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 69.64,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-12",
      label: "计划12",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 68.595,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-13",
      label: "计划13",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 67.565,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "family-byd-plan-14",
      label: "计划14",
      holdingId: "family-002594",
      type: "买入",
      triggerPrice: 66.55,
      shares: 200,
      status: "未触发",
      note: "",
      applied: false
    },
    {
      id: "cjdl-plan-1",
      label: "计划1",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 26,
      shares: null,
      status: "未触发",
      note: "26-28 小额打底",
      applied: false
    },
    {
      id: "cjdl-plan-2",
      label: "计划2",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 25,
      shares: null,
      status: "未触发",
      note: "25-26 正常补仓",
      applied: false
    },
    {
      id: "cjdl-plan-3",
      label: "计划3",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 23,
      shares: null,
      status: "未触发",
      note: "23-25 加速补仓",
      applied: false
    },
    {
      id: "cjdl-plan-4",
      label: "计划4",
      holdingId: "family-600900",
      type: "买入",
      triggerPrice: 22,
      shares: null,
      status: "未触发",
      note: "22 以下重点补仓",
      applied: false
    },
    {
      id: "cjdl-plan-5",
      label: "计划5",
      holdingId: "family-600900",
      type: "卖出",
      triggerPrice: 31,
      shares: null,
      status: "未触发",
      note: "31 以上评估减仓",
      applied: false
    },
    {
      id: "cjdl-plan-6",
      label: "计划6",
      holdingId: "family-600900",
      type: "卖出",
      triggerPrice: 33,
      shares: null,
      status: "未触发",
      note: "33 以上明显偏贵，可减一部分",
      applied: false
    },
    {
      id: "cjdl-plan-7",
      label: "计划7",
      holdingId: "family-600900",
      type: "卖出",
      triggerPrice: 37,
      shares: null,
      status: "未触发",
      note: "梦想价位，可大幅减仓",
      applied: false
    },
    {
      id: "cmb-plan-1",
      label: "计划1",
      holdingId: "family-600036",
      type: "观察",
      triggerPrice: null,
      shares: null,
      status: "未触发",
      note: "等待风控通过后再分批增持",
      applied: false
    },
    {
      id: "zjgk-plan-1",
      label: "计划1",
      holdingId: "family-600895",
      type: "观察",
      triggerPrice: 37.64,
      shares: 600,
      status: "未触发",
      note: "等待确认卖出计划",
      applied: false
    }
  ]
};
